data:
  filter_length: 1024
  hop_length: 320
  max_wav_value: 32768.0
  mel_channels: 100
  mel_fmax: 16000.0
  mel_fmin: 50.0
  sampling_rate: 32000
  segment_size: 8000
  training_files: files/train.txt
  validation_files: files/valid.txt
  win_length: 1024
dist_config:
  dist_backend: nccl
  dist_url: tcp://localhost:54321
  world_size: 1
epochs: '100'
gen:
  resblock_dilation_sizes:
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  resblock_kernel_sizes:
  - 3
  - 7
  - 11
  upsample_initial_channel: 320
  upsample_input: 192
  upsample_kernel_sizes:
  - 15
  - 8
  - 8
  - 4
  - 4
  upsample_rates:
  - 5
  - 4
  - 4
  - 2
  - 2
log:
  eval_interval: 1
  info_interval: 50
  keep_ckpts: 5
  log_dir: logs
  num_audio: 6
  pth_dir: chkpt
  save_interval: 5
mpd:
  kernel_size: 5
  lReLU_slope: 0.2
  periods:
  - 2
  - 3
  - 5
  - 7
  - 11
  stride: 3
  use_spectral_norm: false
mrd:
  lReLU_slope: 0.2
  resolutions: '[(1024, 120, 600), (2048, 240, 1200), (4096, 480, 2400), (512, 50,
    240)]'
  use_spectral_norm: false
train:
  batch_size: 6
  betas:
  - 0.8
  - 0.99
  c_kl: 0.2
  c_mel: 1.0
  c_stft: 9
  epochs: 100
  eps: 1e-9
  learning_rate: 5.0e-05
  lr_decay: 0.999875
  model: half
  port: 8001
  pretrain: vits_pretrain/sovits5.0.pretrain.pth
  seed: 1234
vits:
  filter_channels: 640
  gin_channels: 256
  hidden_channels: 192
  inter_channels: 192
  ppg_dim: 1280
  spk_dim: 256
  vec_dim: 256
